/// Compile the AST generated by `sntk_core` parser into bytecode.
pub mod compiler;
/// The error module contains the error handling for the parser.
pub mod error;
/// Helper functions for the compiler.
pub mod helpers;
pub mod macros;
/// Type Checker.
pub mod tc;
